appClass: info.magnolia.ui.contentapp.ContentApp
class: info.magnolia.ui.contentapp.ContentAppDescriptor
label: projectdemo.app.trainees.label
icon: icon-user-public
subApps:
  browser:
    subAppClass: info.magnolia.ui.contentapp.browser.BrowserSubApp
    class: info.magnolia.ui.contentapp.browser.BrowserSubAppDescriptor
    label: projectdemo.app.trainees.subapp.label
    actionbar:
      defaultAction: editItem
      sections:
        - name: root
          label: projectdemo.app.trainees.actionbar.sactions.root.label
          groups:
            - name: addActions
              items:
                - name: addItem
                - name: addFolder
          availability:
            nodes: false
            root: true
        - name: folder
          label: projectdemo.app.trainees.actionbar.sactions.folder.label
          groups:
            - name: addActions
              items:
                - name: addItem
                - name: addFolder
            - name: editActions
              items:
                - name: editFolder
                - name: deleteFolder
          availability:
            nodeTypes:
              - mgnl:folder
        - name: trainee
          label: projectdemo.app.trainees.actionbar.sactions.trainee.label
          groups:
            - name: editActions
              items:
                - name: editItem
                - name: deleteItem
                - name: publish
                - name: unpublish
          availability:
            nodeTypes:
              - mgnl:trainee
    actions: !include /projectdemo-main/apps/common/default-app-bar-actions.yaml
    workbench:
      dropConstraintClass: info.magnolia.ui.workbench.tree.drop.AlwaysTrueDropConstraint
      editable: false

      contentViews:
        - name: tree
          class: info.magnolia.ui.workbench.tree.TreePresenterDefinition
          columns: &myColumns
            - name: name
              editable: true
              sortable: true
              propertyName: name
              class: info.magnolia.ui.workbench.column.definition.PropertyColumnDefinition
              label: projectdemo.app.trainees.treeView.traineeNo
            - name: traineeId
              editable: true
              sortable: true
              propertyName: traineeId
              class: info.magnolia.ui.workbench.column.definition.PropertyColumnDefinition
              label: projectdemo.app.trainees.treeView.traineeId
            - name: firstName
              editable: true
              sortable: true
              propertyName: firstName
              class: info.magnolia.ui.workbench.column.definition.PropertyColumnDefinition
              label: projectdemo.app.trainees.treeView.firstName
            - name: lastName
              editable: true
              sortable: true
              propertyName: lastName
              class: info.magnolia.ui.workbench.column.definition.PropertyColumnDefinition
              label: projectdemo.app.trainees.treeView.lastName
            - name: status
              width: 45
              displayInChooseDialog: false
              formatterClass: info.magnolia.ui.workbench.column.StatusColumnFormatter
              class: info.magnolia.ui.workbench.column.definition.StatusColumnDefinition
            - name: moddate
              width: 160
              sortable: true
              displayInChooseDialog: false
              formatterClass: info.magnolia.ui.workbench.column.DateColumnFormatter
              propertyName: mgnl:lastModified
              class: info.magnolia.ui.workbench.column.definition.MetaDataColumnDefinition
        - name: list
          class: info.magnolia.ui.workbench.list.ListPresenterDefinition
          columns: *myColumns
        - name: thumbnail
          class: info.magnolia.ui.workbench.thumbnail.ThumbnailPresenterDefinition
        - name: search
          class: info.magnolia.ui.workbench.search.SearchPresenterDefinition
          columns: *myColumns
    imageProvider:
       class: info.magnolia.dam.app.ui.imageprovider.DamLinkImageProviderDefinition
       damLinkPropertyName: image
    contentConnector:
      includeProperties: false
      workspace: trainees
      rootPath: /
      defaultOrder: name
      nodeTypes:
        - name: mgnl:trainee
          icon: icon-items
        - name: mgnl:folder
          icon: icon-folder
  detail:
    subAppClass: info.magnolia.ui.contentapp.detail.DetailSubApp
    class: info.magnolia.ui.contentapp.detail.DetailSubAppDescriptor
    actions: !include /projectdemo-main/apps/common/default-form-detail-actions.yaml
    editor:
      actions:
        - name: commit
        - name: cancel
      form:
        tabs:
          - name: trainee
            label: projectdemo.app.trainees.tab.trainee.label
            fields:
              - name: name
                class: com.projectdemo.basic.form.field.definition.UniqueAssetIdFieldDefinition
                nodeType: mgnl:trainee
                workspace: trainees
                required: true
                type: Long
                label: projectdemo.app.trainees.form.traineeNo
              - name: traineeId
                class: com.projectdemo.basic.form.field.definition.StringIdentifyFieldDefinition
                required: true
                type: String
                label: projectdemo.app.trainees.form.traineeId
              - name: firstName
                class: info.magnolia.ui.form.field.definition.TextFieldDefinition
                i18n: true
                label: projectdemo.app.trainees.form.firstName
              - name: lastName
                class: info.magnolia.ui.form.field.definition.TextFieldDefinition
                i18n: true
                label: projectdemo.app.trainees.form.lastName
              - name: dateOfBirth
                class: info.magnolia.ui.form.field.definition.DateFieldDefinition
                dateFormat: dd/MM/yyyy
                time: true
                type: Date
                label: projectdemo.app.trainees.form.dateOfBirth
              - name: image
                class: info.magnolia.ui.form.field.definition.LinkFieldDefinition
                targetWorkspace: dam
                appName: assets
                label: projectdemo.app.trainees.form.image
                identifierToPathConverter:
                  class: info.magnolia.dam.app.assets.field.translator.AssetCompositeIdKeyTranslator
                contentPreviewDefinition:
                  contentPreviewClass: info.magnolia.dam.app.ui.field.DamFilePreviewComponent
              - name: joinedDate
                class: com.projectdemo.basic.form.field.definition.AutoFillDateFieldDefinition
                dateFormat: dd/MM/yyyy
                time: true
                type: Date
                required: true
                label: projectdemo.app.trainees.form.joinedDate
              - name: description
                class: info.magnolia.ui.form.field.definition.RichTextFieldDefinition
                i18n: true
                label: projectdemo.app.trainees.form.description
      nodeType:
        icon: icon-items
        name: mgnl:trainee
    contentConnector:
      workspace: trainees